name: work-2
on:
  push:
    branches:
      - main
jobs:
  hello1:
    runs-on: ubuntu-latest
    steps:
      - name: sayBye
        run: echo "Bye"
      - name: sayMyName
        run: echo "${{ github.actor }}"
